#! /bin/bash
DESCRIPTION="Generate iOS Editors' First Edit Timestamp"
QUERY="
SET mapred.job.queue.name=nice;
-- Set compression codec to gzip to provide asked format
SET hive.exec.compress.output=true;
SET mapreduce.output.fileoutputformat.compress.codec=org.apache.hadoop.io.compress.GzipCodec;

DROP TABLE IF EXISTS chelsyx.ios_first_edit_ts;
CREATE EXTERNAL TABLE IF NOT EXISTS chelsyx.ios_first_edit_ts
(
    \`username\`                string  COMMENT 'Global username',
    \`first_app_edit_ts\`       string  COMMENT 'The timestamp of first app edit (iOS or Android)',
    \`first_ios_edit_ts\`       string  COMMENT 'The timestamp of first iOS app edit'
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
LOCATION '/user/chelsyx/ios_first_edit_ts'
;

INSERT OVERWRITE TABLE chelsyx.ios_first_edit_ts
-- Editors who have used a mobile app (Android/iOS)
-- to edit Wikipedia before:
SELECT username, MIN(rev_timestamp) AS first_app_edit_ts, MIN(IF(tag='ios app edit', rev_timestamp, NULL)) AS first_ios_edit_ts
FROM (
-- Editors who have previously used a mobile app to edit visible pages:
SELECT r.rev_user_text AS username, d.ctd_name AS tag, r.rev_timestamp AS rev_timestamp
FROM wmf_raw.mediawiki_change_tag t
INNER JOIN wmf_raw.mediawiki_change_tag_def d ON (
t.snapshot='2019-03'
AND d.snapshot='2019-03'
AND t.ct_tag_id = d.ctd_id
AND t.wiki_db = d.wiki_db
AND d.ctd_name IN ('mobile app edit', 'ios app edit')
)
INNER JOIN wmf_raw.mediawiki_revision r ON (
t.snapshot='2019-03'
AND r.snapshot='2019-03'
AND r.rev_user != 0
AND r.rev_id = t.ct_rev_id
AND r.wiki_db = t.wiki_db
)

UNION ALL

-- Editors who have previously used a mobile app to edit deleted pages:
SELECT a.ar_user_text AS username, d.ctd_name AS tag, a.ar_timestamp AS rev_timestamp
FROM wmf_raw.mediawiki_change_tag t
INNER JOIN wmf_raw.mediawiki_change_tag_def d ON (
t.snapshot='2019-03'
AND d.snapshot='2019-03'
AND t.ct_tag_id = d.ctd_id
AND t.wiki_db = d.wiki_db
AND d.ctd_name IN ('mobile app edit', 'ios app edit')
)
INNER JOIN wmf_raw.mediawiki_archive a ON (
t.snapshot='2019-03'
AND a.snapshot='2019-03'
AND a.ar_user != 0
AND a.ar_rev_id = t.ct_rev_id
AND a.wiki_db = t.wiki_db
)

) AS combined_revisions
GROUP BY username
;
"
THISSCRIPTFILE=`basename "$0"`
RESULTSFILE=~/${THISSCRIPTFILE%.*}_result.txt
{ date ; echo = ; TZ='America/Los_Angeles' date ; echo generated by $THISSCRIPTFILE on $HOSTNAME ; beeline --verbose=true -e "$QUERY" ; } &> $RESULTSFILE